### ISSUE TITLE
Thanks for making this!

### ISSUE THREAD

**Issue by TheAngryByrd** [Freymaurer/Fable.Pyxpecto#1]
I just wanna say thanks for making this! This made it trivial to [support FsToolkit.Errorhandling for Python](https://github.com/demystifyfp/FsToolkit.ErrorHandling/pull/227).

**Comment by Freymaurer** [comment]
Thanks man! I really appreciate it! Credit for the domain design goes to @Zaid-Ajaj in Fable.Mocha 😄
