### ISSUE TITLE
Don't throw an exception when exiting with errors

### ISSUE THREAD

**Issue by MangelMaxime** [Freymaurer/Fable.Pyxpecto#3]
Hello,

Currently when a test fail, Fable.Pyxpecto raise an exception at the top level.

But I don't think the exception add usable information:

![CleanShot 2023-11-20 at 21 29 06](https://github.com/Freymaurer/Fable.Pyxpecto/assets/4760796/26d6e85d-36ba-4618-b5f2-1d08c7a57b62)

Here, the exception just tells me that the exception is generated in the file `Main.fs` where I called `Pyxpecto.runTests`.

I believe the important information in this case is the summary report that we can see above that exception. 

What do you think? Would you be open to replace the exception with just a `print`?

**Comment by Freymaurer** [comment]
I had this as failwith, as i was not sure if the exit codes handle everything correctly alone. But, i tested it and changed it to prints 👍 😅 

I also found an issue where i did not correctly handle errors, now it will be exit code 1 for failed tests and exit code 2 for actual errors (such as divide by zero for example).

**Comment by Freymaurer** [comment]
v0.3.0 is released and should soon be available on nuget.
